# Change these first
owner: RivoDani # Your GitHub organization or username, where this repository lives
repo: rivodanicom-upptime # The name of this repository

sites:
  - name: RivoDani.com
    url: https://rivodani.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.rivodani.com
  # baseUrl: /your-repo-name
  logoUrl: https://www.rivodani.com/wp-content/uploads/2023/02/cropped-Logo.png
  name: RivoDani.com Status
  theme: night
  favicon: https://www.rivodani.com/wp-content/uploads/2023/02/cropped-Logo-1-32x32.png
  introTitle: "Esta é página de status de **RivoDani.com**."
  introMessage: Nesta página encontram-se os estados dos nossos serviços. Caso exista algum problema é nesta página que será mostrado.
  navbar:
    - title: Status
      href: /
    - title: RivoDani.com
      href: https://rivodani.com/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  css: "footer p { display: none }"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
